<?php

namespace Database\Seeders;

use App\Models\Ville;
use Illuminate\Database\Seeder;

class VilleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ville::create([
                ["id"=>1,"ville" =>'Aïn Harrouda',"region" => 1],
                ["id"=>2,"ville" =>'Ben Yakhlef',"region" => 1],
                ["id"=>3,"ville" =>'Bouskoura',"region" => 1],
                ["id"=>4,"ville" =>'Casablanca',"region" => 1],
                ["id"=>5,"ville" =>'Médiouna',"region" => 1],
                ["id"=>6,"ville" =>'Mohammédia',"region" => 1],
                ["id"=>7,"ville" =>'Tit Mellil',"region" => 1],
                ["id"=>8,"ville" =>'Ben Yakhlef',"region" => 1],
                ["id"=>9,"ville" =>'Bejaâd',"region" => 1],
                ["id"=>10,"ville" =>'Ben Ahmed',"region" => 1],
                ["id"=>11,"ville" =>'Benslimane',"region" => 1],
                ["id"=>12,"ville" =>'Berrechid',"region" => 1],
                ["id"=>13,"ville" =>'Boujniba',"region" => 1],
                ["id"=>14,"ville" =>'Boulanouare',"region" => 1],
                ["id"=>15,"ville" =>'Bouznika',"region" => 1],
                ["id"=>16,"ville" =>'Deroua',"region" => 1],
                ["id"=>17,"ville" =>'El Borouj',"region" => 1],
                ["id"=>18,"ville" =>'El Gara',"region" => 1],
                ["id"=>19,"ville" =>'Guisser',"region" => 1],
                ["id"=>20,"ville" =>'Hattane',"region" => 1],
                ["id"=>21,"ville" =>'Khouribga',"region" => 1],
                ["id"=>22,"ville" =>'Loulad',"region" => 1],
                ["id"=>23,"ville" =>'Oued Zem',"region" => 1],
                ["id"=>24,"ville" =>'Oulad Abbou',"region" => 1],
                ["id"=>25,"ville" =>'Oulad H Riz Sahel',"region" => 1],
                ["id"=>26,"ville" =>'Oulad M rah',"region" => 1],
                ["id"=>27,"ville" =>'Oulad Saïd',"region" => 1],
                ["id"=>28,"ville" =>'Oulad Sidi Ben Daoud',"region" => 1],
                ["id"=>29,"ville" =>'Ras El Aïn',"region" => 1],
                ["id"=>30,"ville" =>'Settat',"region" => 1],
                ["id"=>31,"ville" =>'Sidi Rahhal Chataï',"region" => 1],
                ["id"=>32,"ville" =>'Soualem',"ville" =>2],
                ["id"=>33,"ville" =>'Azemmour',"region" => 1],
                ["id"=>34,"ville" =>'Bir Jdid',"region" => 1],
                ["id"=>35,"ville" =>'Bouguedra',"region" => 1],
                ["id"=>36,"ville" =>'Echemmaia',"region" => 1],
                ["id"=>37,"ville" =>'El Jadida',"region" => 1],
                ["id"=>38,"ville" =>'Hrara',"region" => 1],
                ["id"=>39,"ville" =>'Ighoud',"region" => 1],
                ["id"=>40,"ville" =>'Jamâat Shaim',"region" => 1],
                ["id"=>41,"ville" =>'Jorf Lasfar',"region" => 1],
                ["id"=>42,"ville" =>'Khemis Zemamra',"region" => 1],
                ["id"=>43,"ville" =>'Laaounate',"region" => 1],
                ["id"=>44,"ville" =>'Moulay Abdallah',"region" => 1],
                ["id"=>45,"ville" =>'Oualidia',"region" => 1],
                ["id"=>46,"ville" =>'Oulad Amrane',"region" => 1],
                ["id"=>47,"ville" =>'Oulad Frej',"region" => 1],
                ["id"=>48,"ville" =>'Oulad Ghadbane',"region" => 1],
                ["id"=>49,"ville" =>'Safi',"region" => 1],
                ["id"=>50,"ville" =>'Sebt El Maârif',"region" => 1],
                ["id"=>51,"ville" =>'Sebt Gzoula',"region" => 1],
                ["id"=>52,"ville" =>'Sidi Ahmed',"region" => 1],
                ["id"=>53,"ville" =>'Sidi Ali Ban Hamdouche',"region" => 1],
                ["id"=>54,"ville" =>'Sidi Bennour',"region" => 1],
                ["id"=>55,"ville" =>'Sidi Bouzid',"region" => 1],
                ["id"=>56,"ville" =>'Sidi Smaïl',"region" => 1],
                ["id"=>57,"ville" =>'Youssoufia',"region" => 1],
                ["id"=>58,"ville" =>'Fès',"region" => 1],
                ["id"=>59,"ville" =>'Aïn Cheggag',"region" => 1],
                ["id"=>60,"ville" =>'Bhalil',"region" => 1],
                ["id"=>61,"ville" =>'Boulemane',"region" => 1],
                ["id"=>62,"ville" =>'El Menzel',"region" => 1],
                ["id"=>63,"ville" =>'Guigou',"region" => 1],
                ["id"=>64,"ville" =>'Imouzzer Kandar',"region" => 1],
                ["id"=>65,"ville" =>'Imouzzer Marmoucha',"region" => 1],
                ["id"=>66,"ville" =>'Missour',"region" => 1],
                ["id"=>67,"ville" =>'Moulay Yaâcoub',"region" => 1],
                ["id"=>68,"ville" =>'Ouled Tayeb',"region" => 1],
                ["id"=>69,"ville" =>'Outat El Haj',"region" => 1],
                ["id"=>70,"ville" =>'Ribate El Kheir',"region" => 1],
                ["id"=>71,"ville" =>'Séfrou',"region" => 1],
                ["id"=>72,"ville" =>'Skhinate',"region" => 1],
                ["id"=>73,"ville" =>'Tafajight',"region" => 1],
                ["id"=>74,"ville" =>'Arbaoua',"region" => 1],
                ["id"=>75,"ville" =>'Aïn Dorij',"region" => 1],
                ["id"=>76,"ville" =>'Dar Gueddari',"region" => 1],
                ["id"=>77,"ville" =>'Had Kourt',"region" => 1],
                ["id"=>78,"ville" =>'Jorf El Melha',"region" => 1],
                ["id"=>79,"ville" =>'Kénitra',"region" => 1],
                ["id"=>80,"ville" =>'Khenichet',"region" => 1],
                ["id"=>81,"ville" =>'Lalla Mimouna',"region" => 1],
                ["id"=>82,"ville" =>'Mechra Bel Ksiri',"region" => 1],
                ["id"=>83,"ville" =>'Mehdia',"region" => 1],
                ["id"=>84,"ville" =>'Moulay Bousselham',"region" => 1],
                ["id"=>85,"ville" =>'Sidi Allal Tazi',"region" => 1],
                ["id"=>86,"ville" =>'Sidi Kacem',"region" => 1],
                ["id"=>87,"ville" =>'Sidi Slimane',"region" => 1],
                ["id"=>88,"ville" =>'Sidi Taibi',"region" => 1],
                ["id"=>89,"ville" =>'Sidi Yahya El Gharb',"region" => 1],
                ["id"=>90,"ville" =>'Souk El Arbaa',"region" => 1],
                ["id"=>91,"ville" =>'Akka',"region" => 1],
                ["id"=>92,"ville" =>'Assa',"region" => 1],
                ["id"=>93,"ville" =>'Bouizakarne',"region" => 1],
                ["id"=>94,"ville" =>'El Ouatia',"region" => 1],
                ["id"=>95,"ville" =>'Es-Semara',"region" => 1],
                ["id"=>96,"ville" =>'Fam El Hisn',"region" => 1],
                ["id"=>97,"ville" =>'Foum Zguid',"region" => 1],
                ["id"=>98,"ville" =>'Guelmim',"region" => 1],
                ["id"=>99,"ville" =>'Taghjijt',"region" => 1],
                ["id"=>100,"ville" =>'Tan-Tan',"region" => 1],
                ["id"=>101,"ville" =>'Tata',"region" => 1],
                ["id"=>102,"ville" =>'Zag',"region" => 1],
                ["id"=>103,"ville" =>'Marrakech',"region" => 1],
                ["id"=>104,"ville" =>'Ait Daoud',"region" => 1],
                ["id"=>115,"ville" =>'Amizmiz',"region" => 1],
                ["id"=>116,"ville" =>'Assahrij',"region" => 1],
                ["id"=>117,"ville" =>'Aït Ourir',"region" => 1],
                ["id"=>118,"ville" =>'Ben Guerir',"region" => 1],
                ["id"=>119,"ville" =>'Chichaoua',"region" => 1],
                ["id"=>120,"ville" =>'El Hanchane',"region" => 1],
                ["id"=>121,"ville" =>'El Kelaâ des Sraghna',"region" => 1],
                ["id"=>122,"ville" =>'Essaouira',"region" => 1],
                ["id"=>123,"ville" =>'Fraïta',"region" => 1],
                ["id"=>124,"ville" =>'Ghmate',"region" => 1],
                ["id"=>125,"ville" =>'Ighounane',"region" => 1],
                ["id"=>126,"ville" =>'Imintanoute',"region" => 1],
                ["id"=>127,"ville" =>'Kattara',"region" => 1],
                ["id"=>128,"ville" =>'Lalla Takerkoust',"region" => 1],
                ["id"=>129,"ville" =>'Loudaya',"region" => 1],
                ["id"=>130,"ville" =>'Lâattaouia',"region" => 1],
                ["id"=>131,"ville" =>'Moulay Brahim',"region" => 1],
                ["id"=>132,"ville" =>'Mzouda',"region" => 1],
                ["id"=>133,"ville" =>'Ounagha',"region" => 1],
                ["id"=>134,"ville" =>'Sid L Mokhtar',"region" => 1],
                ["id"=>135,"ville" =>'Sid Zouin',"region" => 1],
                ["id"=>136,"ville" =>'Sidi Abdallah Ghiat',"region" => 1],
                ["id"=>137,"ville" =>'Sidi Bou Othmane',"region" => 1],
                ["id"=>138,"ville" =>'Sidi Rahhal',"region" => 1],
                ["id"=>139,"ville" =>'Skhour Rehamna',"region" => 1],
                ["id"=>140,"ville" =>'Smimou',"region" => 1],
                ["id"=>141,"ville" =>'Tafetachte',"region" => 1],
                ["id"=>142,"ville" =>'Tahannaout',"region" => 1],
                ["id"=>143,"ville" =>'Talmest',"region" => 1],
                ["id"=>144,"ville" =>'Tamallalt',"region" => 1],
                ["id"=>145,"ville" =>'Tamanar',"region" => 1],
                ["id"=>146,"ville" =>'Tamansourt',"region" => 1],
                ["id"=>147,"ville" =>'Tameslouht',"region" => 1],
                ["id"=>148,"ville" =>'Tanalt',"region" => 1],
                ["id"=>149,"ville" =>'Zeubelemok',"region" => 1],
                ["id"=>150,"ville" =>'Meknès?',"region" => 1],
                ["id"=>151,"ville" =>'Khénifra',"region" => 1],
                ["id"=>152,"ville" =>'Agourai',"region" => 1],
                ["id"=>153,"ville" =>'Ain Taoujdate',"region" => 1],
                ["id"=>154,"ville" =>'MyAliCherif',"region" => 1],
                ["id"=>155,"ville" =>'Rissani',"region" => 1],
                ["id"=>156,"ville" =>'Amalou Ighriben',"region" => 1],
                ["id"=>157,"ville" =>'Aoufous',"region" => 1],
                ["id"=>158,"ville" =>'Arfoud',"region" => 1],
                ["id"=>159,"ville" =>'Azrou',"region" => 1],
                ["id"=>160,"ville" =>'Aïn Jemaa',"region" => 1],
                ["id"=>161,"ville" =>'Aïn Karma',"region" => 1],
                ["id"=>162,"ville" =>'Aïn Leuh',"region" => 1],
                ["id"=>163,"ville" =>'Aït Boubidmane',"region" => 1],
                ["id"=>164,"ville" =>'Aït Ishaq',"region" => 1],
                ["id"=>165,"ville" =>'Boudnib',"region" => 1],
                ["id"=>166,"ville" =>'Boufakrane',"region" => 1],
                ["id"=>167,"ville" =>'Boumia',"region" => 1],
                ["id"=>168,"ville" =>'El Hajeb',"region" => 1],
                ["id"=>169,"ville" =>'Elkbab',"region" => 1],
                ["id"=>170,"ville" =>'Er-Rich',"region" => 1],
                ["id"=>171,"ville" =>'Errachidia',"region" => 1],
                ["id"=>172,"ville" =>'Gardmit',"region" => 1],
                ["id"=>173,"ville" =>'Goulmima',"region" => 1],
                ["id"=>174,"ville" =>'Gourrama',"region" => 1],
                ["id"=>175,"ville" =>'Had Bouhssoussen',"region" => 1],
                ["id"=>176,"ville" =>'Haj Kaddour',"region" => 1],
                ["id"=>177,"ville" =>'Ifrane',"region" => 1],
                ["id"=>178,"ville" =>'Itzer',"region" => 1],
                ["id"=>179,"ville" =>'Jorf',"region" => 1],
                ["id"=>180,"ville" =>'Kehf Nsour',"region" => 1],
                ["id"=>181,"ville" =>'Kerrouchen',"region" => 1],
                ["id"=>182,"ville" =>'M haya',"region" => 1],
                ["id"=>183,"ville" =>'M rirt',"region" => 1],
                ["id"=>184,"ville" =>'Midelt',"region" => 1],
                ["id"=>185,"ville" =>'Moulay Ali Cherif',"region" => 1],
                ["id"=>186,"ville" =>'Moulay Bouazza',"region" => 1],
                ["id"=>187,"ville" =>'Moulay Idriss Zerhoun',"region" => 1],
                ["id"=>188,"ville" =>'Moussaoua',"region" => 1],
                ["id"=>189,"ville" =>'N Zalat Bni Amar',"region" => 1],
                ["id"=>190,"ville" =>'Ouaoumana',"region" => 1],
                ["id"=>191,"ville" =>'Oued Ifrane',"region" => 1],
                ["id"=>192,"ville" =>'Sabaa Aiyoun',"region" => 1],
                ["id"=>193,"ville" =>'Sebt Jahjouh',"region" => 1],
                ["id"=>194,"ville" =>'Sidi Addi',"region" => 1],
                ["id"=>195,"ville" =>'Tichoute',"region" => 1],
                ["id"=>196,"ville" =>'Tighassaline',"region" => 1],
                ["id"=>197,"ville" =>'Tighza',"region" => 1],
                ["id"=>198,"ville" =>'Timahdite',"region" => 1],
                ["id"=>199,"ville" =>'Tinejdad',"region" => 1],
                ["id"=>200,"ville" =>'Tizguite',"region" => 1],
                ["id"=>201,"ville" =>'Toulal',"region" => 1],
                ["id"=>202,"ville" =>'Tounfite',"region" => 1],
                ["id"=>203,"ville" =>'Zaouia Ifrane',"region" => 1],
                ["id"=>204,"ville" =>'Zaïda',"region" => 1],
                ["id"=>205,"ville" =>'Ahfir',"region" => 1],
                ["id"=>206,"ville" =>'Aklim',"region" => 1],
                ["id"=>207,"ville" =>'Al Aroui',"region" => 1],
                ["id"=>208,"ville" =>'Aïn Bni Mathar',"region" => 1],
                ["id"=>209,"ville" =>'Aïn Erreggada',"region" => 1],
                ["id"=>210,"ville" =>'Ben Taïeb',"region" => 1],
                ["id"=>211,"ville" =>'Berkane',"region" => 1],
                ["id"=>212,"ville" =>'Bni Ansar',"region" => 1],
                ["id"=>213,"ville" =>'Bni Chiker',"region" => 1],
                ["id"=>214,"ville" =>'Bni Drar',"region" => 1],
                ["id"=>215,"ville" =>'Bni Tadjite',"region" => 1],
                ["id"=>216,"ville" =>'Bouanane',"region" => 1],
                ["id"=>217,"ville" =>'Bouarfa',"region" => 1],
                ["id"=>218,"ville" =>'Bouhdila',"region" => 1],
                ["id"=>219,"ville" =>'Dar El Kebdani',"region" => 1],
                ["id"=>220,"ville" =>'Debdou',"region" => 1],
                ["id"=>221,"ville" =>'Douar Kannine',"region" => 1],
                ["id"=>222,"ville" =>'Driouch',"region" => 1],
                ["id"=>223,"ville" =>'El Aïoun Sidi Mellouk',"region" => 1],
                ["id"=>224,"ville" =>'Farkhana',"region" => 1],
                ["id"=>225,"ville" =>'Figuig',"region" => 1],
                ["id"=>226,"ville" =>'Ihddaden',"region" => 1],
                ["id"=>227,"ville" =>'Jaâdar',"region" => 1],
                ["id"=>228,"ville" =>'Jerada',"region" => 1],
                ["id"=>229,"ville" =>'Kariat Arekmane',"region" => 1],
                ["id"=>230,"ville" =>'Kassita',"region" => 1],
                ["id"=>231,"ville" =>'Kerouna',"region" => 1],
                ["id"=>232,"ville" =>'Laâtamna',"region" => 1],
                ["id"=>233,"ville" =>'Madagh',"region" => 1],
                ["id"=>234,"ville" =>'Midar',"region" => 1],
                ["id"=>235,"ville" =>'Nador',"region" => 1],
                ["id"=>236,"ville" =>'Naima',"region" => 1],
                ["id"=>237,"ville" =>'Oued Heimer',"region" => 1],
                ["id"=>238,"ville" =>'Oujda',"region" => 1],
                ["id"=>239,"ville" =>'Ras El Ma',"region" => 1],
                ["id"=>240,"ville" =>'Saïdia',"region" => 1],
                ["id"=>241,"ville" =>'Selouane',"region" => 1],
                ["id"=>242,"ville" =>'Sidi Boubker',"region" => 1],
                ["id"=>243,"ville" =>'Sidi Slimane Echcharaa',"region" => 1],
                ["id"=>244,"ville" =>'Talsint',"region" => 1],
                ["id"=>245,"ville" =>'Taourirt',"region" => 1],
                ["id"=>246,"ville" =>'Tendrara',"region" => 1],
                ["id"=>247,"ville" =>'Tiztoutine',"region" => 1],
                ["id"=>248,"ville" =>'Touima',"region" => 1],
                ["id"=>249,"ville" =>'Touissit',"region" => 1],
                ["id"=>250,"ville" =>'Zaïo',"region" => 1],
                ["id"=>251,"ville" =>'Zeghanghane',"region" => 1],
                ["id"=>252,"ville" =>'Rabat',"region" => 1],
                ["id"=>253,"ville" =>'Salé',"region" => 1],
                ["id"=>254,"ville" =>'Ain El Aouda',"region" => 1],
                ["id"=>255,"ville" =>'Harhoura',"region" => 1],
                ["id"=>256,"ville" =>'Khémisset',"region" => 1],
                ["id"=>257,"ville" =>'Oulmès',"region" => 1],
                ["id"=>258,"ville" =>'Rommani',"region" => 1],
                ["id"=>259,"ville" =>'Sidi Allal El Bahraoui',"region" => 1],
                ["id"=>260,"ville" =>'Sidi Bouknadel',"region" => 1],
                ["id"=>261,"ville" =>'Skhirat',"region" => 1],
                ["id"=>262,"ville" =>'Tamesna',"region" => 1],
                ["id"=>263,"ville" =>'Témara',"region" => 1],
                ["id"=>264,"ville" =>'Tiddas',"region" => 1],
                ["id"=>265,"ville" =>'Tiflet',"region" => 1],
                ["id"=>266,"ville" =>'Touarga',"region" => 1],
                ["id"=>267,"ville" =>'Agadir',"region" => 1],
                ["id"=>268,"ville" =>'Agdz',"region" => 1],
                ["id"=>269,"ville" =>'Agni Izimmer',"region" => 1],
                ["id"=>270,"ville" =>'Aït Melloul',"region" => 1],
                ["id"=>271,"ville" =>'Alnif',"region" => 1],
                ["id"=>272,"ville" =>'Anzi',"region" => 1],
                ["id"=>273,"ville" =>'Aoulouz',"region" => 1],
                ["id"=>274,"ville" =>'Aourir',"region" => 1],
                ["id"=>275,"ville" =>'Arazane',"region" => 1],
                ["id"=>276,"ville" =>'Aït Baha',"region" => 1],
                ["id"=>277,"ville" =>'Aït Iaâza',"region" => 1],
                ["id"=>278,"ville" =>'Aït Yalla',"region" => 1],
                ["id"=>279,"ville" =>'Ben Sergao',"region" => 1],
                ["id"=>280,"ville" =>'Biougra',"region" => 1],
                ["id"=>281,"ville" =>'Boumalne-Dadès',"region" => 1],
                ["id"=>282,"ville" =>'Dcheira El Jihadia',"region" => 1],
                ["id"=>283,"ville" =>'Drargua',"region" => 1],
                ["id"=>284,"ville" =>'El Guerdane',"region" => 1],
                ["id"=>285,"ville" =>'Harte Lyamine',"region" => 1],
                ["id"=>286,"ville" =>'Ida Ougnidif',"region" => 1],
                ["id"=>287,"ville" =>'Ifri',"region" => 1],
                ["id"=>288,"ville" =>'Igdamen',"region" => 1],
                ["id"=>289,"ville" =>'Ighil n Oumgoun',"region" => 1],
                ["id"=>290,"ville" =>'Imassine',"region" => 1],
                ["id"=>291,"ville" =>'Inezgane',"region" => 1],
                ["id"=>292,"ville" =>'Irherm',"region" => 1],
                ["id"=>293,"ville" =>'Kelaat-M Gouna',"region" => 1],
                ["id"=>294,"ville" =>'Lakhsas',"region" => 1],
                ["id"=>295,"ville" =>'Lakhsass',"region" => 1],
                ["id"=>296,"ville" =>'Lqliâa',"region" => 1],
                ["id"=>297,"ville" =>'M semrir',"region" => 1],
                ["id"=>298,"ville" =>'Massa ["id"=>Maroc]',"region" => 1],
                ["id"=>299,"ville" =>'Megousse',"region" => 1],
                ["id"=>300,"ville" =>'Ouarzazate',"region" => 1],
                ["id"=>301,"ville" =>'Oulad Berhil',"region" => 1],
                ["id"=>302,"ville" =>'Oulad Teïma',"region" => 1],
                ["id"=>303,"ville" =>'Sarghine',"region" => 1],
                ["id"=>304,"ville" =>'Sidi Ifni',"region" => 1],
                ["id"=>305,"ville" =>'Skoura',"region" => 1],
                ["id"=>306,"ville" =>'Tabounte',"region" => 1],
                ["id"=>307,"ville" =>'Tafraout',"region" => 1],
                ["id"=>308,"ville" =>'Taghzout',"region" => 1],
                ["id"=>309,"ville" =>'Tagzen',"region" => 1],
                ["id"=>310,"ville" =>'Taliouine',"region" => 1],
                ["id"=>311,"ville" =>'Tamegroute',"region" => 1],
                ["id"=>312,"ville" =>'Tamraght',"region" => 1],
                ["id"=>313,"ville" =>'Tanoumrite Nkob Zagora',"region" => 1],
                ["id"=>314,"ville" =>'Taourirt ait zaghar',"region" => 1],
                ["id"=>315,"ville" =>'Taroudant',"region" => 1],
                ["id"=>316,"ville" =>'Temsia',"region" => 1],
                ["id"=>317,"ville" =>'Tifnit',"region" => 1],
                ["id"=>318,"ville" =>'Tisgdal',"region" => 1],
                ["id"=>319,"ville" =>'Tiznit',"region" => 1],
                ["id"=>320,"ville" =>'Toundoute',"region" => 1],
                ["id"=>321,"ville" =>'Zagora',"region" => 1],
                ["id"=>322,"ville" =>'Afourar',"region" => 1],
                ["id"=>323,"ville" =>'Aghbala',"region" => 1],
                ["id"=>324,"ville" =>'Azilal',"region" => 1],
                ["id"=>325,"ville" =>'Aït Majden',"region" => 1],
                ["id"=>326,"ville" =>'Beni Ayat',"region" => 1],
                ["id"=>327,"ville" =>'Béni Mellal',"region" => 1],
                ["id"=>328,"ville" =>'Bin elouidane',"region" => 1],
                ["id"=>329,"ville" =>'Bradia',"region" => 1],
                ["id"=>330,"ville" =>'Bzou',"region" => 1],
                ["id"=>331,"ville" =>'Dar Oulad Zidouh',"region" => 1],
                ["id"=>332,"ville" =>'Demnate',"region" => 1],
                ["id"=>333,"ville" =>'Dra a',"region" => 1],
                ["id"=>334,"ville" =>'El Ksiba',"region" => 1],
                ["id"=>335,"ville" =>'Foum Jamaa',"region" => 1],
                ["id"=>336,"ville" =>'Fquih Ben Salah',"region" => 1],
                ["id"=>337,"ville" =>'Kasba Tadla',"region" => 1],
                ["id"=>338,"ville" =>'Ouaouizeght',"region" => 1],
                ["id"=>339,"ville" =>'Oulad Ayad',"region" => 1],
                ["id"=>340,"ville" =>'Oulad M Barek',"region" => 1],
                ["id"=>341,"ville" =>'Oulad Yaich',"region" => 1],
                ["id"=>342,"ville" =>'Sidi Jaber',"region" => 1],
                ["id"=>343,"ville" =>'Souk Sebt Oulad Nemma',"region" => 1],
                ["id"=>344,"ville" =>'Zaouïat Cheikh',"region" => 1],
                ["id"=>345,"ville" =>'Tanger',"region" => 1],
                ["id"=>346,"ville" =>'Tétouan',"region" => 1],
                ["id"=>347,"ville" =>'Akchour',"region" => 1],
                ["id"=>348,"ville" =>'Assilah',"region" => 1],
                ["id"=>349,"ville" =>'Bab Berred',"region" => 1],
                ["id"=>350,"ville" =>'Bab Taza',"region" => 1],
                ["id"=>351,"ville" =>'Brikcha',"region" => 1],
                ["id"=>352,"ville" =>'Chefchaouen',"region" => 1],
                ["id"=>353,"ville" =>'Dar Bni Karrich',"region" => 1],
                ["id"=>354,"ville" =>'Dar Chaoui',"region" => 1],
                ["id"=>355,"ville" =>'Fnideq',"region" => 1],
                ["id"=>356,"ville" =>'Gueznaia',"region" => 1],
                ["id"=>357,"ville" =>'Jebha',"region" => 1],
                ["id"=>358,"ville" =>'Karia',"region" => 1],
                ["id"=>359,"ville" =>'Khémis Sahel',"region" => 1],
                ["id"=>360,"ville" =>'Ksar El Kébir',"region" => 1],
                ["id"=>361,"ville" =>'Larache',"region" => 1],
                ["id"=>362,"ville" =>'M diq',"region" => 1],
                ["id"=>363,"ville" =>'Martil',"region" => 1],
                ["id"=>364,"ville" =>'Moqrisset',"region" => 1],
                ["id"=>365,"ville" =>'Oued Laou',"region" => 1],
                ["id"=>366,"ville" =>'Oued Rmel',"region" => 1],
                ["id"=>367,"ville" =>'Ouezzane',"region" => 1],
                ["id"=>368,"ville" =>'Point Cires',"region" => 1],
                ["id"=>369,"ville" =>'Sidi Lyamani',"region" => 1],
                ["id"=>370,"ville" =>'Sidi Mohamed ben Abdallah el-Raisuni',"region" => 1],
                ["id"=>371,"ville" =>'Zinat',"region" => 1],
                ["id"=>372,"ville" =>'Ajdir',"region" => 1],
                ["id"=>373,"ville" =>'Aknoul',"region" => 1],
                ["id"=>374,"ville" =>'Al Hoceïma',"region" => 1],
                ["id"=>375,"ville" =>'Aït Hichem',"region" => 1],
                ["id"=>376,"ville" =>'Bni Bouayach',"region" => 1],
                ["id"=>377,"ville" =>'Bni Hadifa',"region" => 1],
                ["id"=>378,"ville" =>'Ghafsai',"region" => 1],
                ["id"=>379,"ville" =>'Guercif',"region" => 1],
                ["id"=>380,"ville" =>'Imzouren',"region" => 1],
                ["id"=>381,"ville" =>'Inahnahen',"region" => 1],
                ["id"=>382,"ville" =>'Issaguen ["id"=>Ketama]',"region" => 1],
                ["id"=>383,"ville" =>'Karia ["id"=>El Jadida]',"region" => 1],
                ["id"=>384,"ville" =>'Karia Ba Mohamed',"region" => 1],
                ["id"=>385,"ville" =>'Oued Amlil',"region" => 1],
                ["id"=>386,"ville" =>'Oulad Zbair',"region" => 1],
                ["id"=>387,"ville" =>'Tahla',"region" => 1],
                ["id"=>388,"ville" =>'Tala Tazegwaght',"region" => 1],
                ["id"=>389,"ville" =>'Tamassint',"region" => 1],
                ["id"=>390,"ville" =>'Taounate',"region" => 1],
                ["id"=>391,"ville" =>'Targuist',"region" => 1],
                ["id"=>392,"ville" =>'Taza',"region" => 1],
                ["id"=>393,"ville" =>'Taïnaste',"region" => 1],
                ["id"=>394,"ville" =>'Thar Es-Souk',"region" => 1],
                ["id"=>395,"ville" =>'Tissa',"region" => 1],
                ["id"=>396,"ville" =>'Tizi Ouasli',"region" => 1],
                ["id"=>397,"ville" =>'Laayoune',"region" => 1],
                ["id"=>398,"ville" =>'El Marsa',"region" => 1],
                ["id"=>399,"ville" =>'Tarfaya',"region" => 1],
                ["id"=>400,"ville" =>'Boujdour',"region" => 1],
                ["id"=>401,"ville" =>'Awsard',"region" => 1],
                ["id"=>402,"ville" =>'Oued-Eddahab ',"region" => 1],
                ["id"=>403,"ville" =>'Stehat',"region" => 1],
                ["id"=>404,"ville" =>'Aït Attab',"region" => 1]
        ]);
    }
}
