<?php

namespace Database\Seeders;

use App\Models\Ville;
use Illuminate\Database\Seeder;

class VilleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ville::create(
                [1, 'Aïn Harrouda', 1],
                [2, 'Ben Yakhlef', 1],
                [3, 'Bouskoura', 1],
                [4, 'Casablanca', 1],
                [5, 'Médiouna', 1],
                [6, 'Mohammédia', 1],
                [7, 'Tit Mellil', 1],
                [8, 'Ben Yakhlef', 1],
                [9, 'Bejaâd', 1],
                [10, 'Ben Ahmed', 1],
                [11, 'Benslimane', 1],
                [12, 'Berrechid', 1],
                [13, 'Boujniba', 1],
                [14, 'Boulanouare', 1],
                [15, 'Bouznika', 1],
                [16, 'Deroua', 1],
                [17, 'El Borouj', 1],
                [18, 'El Gara', 1],
                [19, 'Guisser', 1],
                [20, 'Hattane', 1],
                [21, 'Khouribga', 1],
                [22, 'Loulad', 1],
                [23, 'Oued Zem', 1],
                [24, 'Oulad Abbou', 1],
                [25, 'Oulad H Riz Sahel', 1],
                [26, 'Oulad M rah', 1],
                [27, 'Oulad Saïd', 1],
                [28, 'Oulad Sidi Ben Daoud', 1],
                [29, 'Ras El Aïn', 1],
                [30, 'Settat', 1],
                [31, 'Sidi Rahhal Chataï', 1],
                [32, 'Soualem', 2],
                [33, 'Azemmour', 1],
                [34, 'Bir Jdid', 1],
                [35, 'Bouguedra', 1],
                [36, 'Echemmaia', 1],
                [37, 'El Jadida', 1],
                [38, 'Hrara', 1],
                [39, 'Ighoud', 1],
                [40, 'Jamâat Shaim', 1],
                [41, 'Jorf Lasfar', 1],
                [42, 'Khemis Zemamra', 1],
                [43, 'Laaounate', 1],
                [44, 'Moulay Abdallah', 1],
                [45, 'Oualidia', 1],
                [46, 'Oulad Amrane', 1],
                [47, 'Oulad Frej', 1],
                [48, 'Oulad Ghadbane', 1],
                [49, 'Safi', 1],
                [50, 'Sebt El Maârif', 1],
                [51, 'Sebt Gzoula', 1],
                [52, 'Sidi Ahmed', 1],
                [53, 'Sidi Ali Ban Hamdouche', 1],
                [54, 'Sidi Bennour', 1],
                [55, 'Sidi Bouzid', 1],
                [56, 'Sidi Smaïl', 1],
                [57, 'Youssoufia', 1],
                [58, 'Fès', 1],
                [59, 'Aïn Cheggag', 1],
                [60, 'Bhalil', 1],
                [61, 'Boulemane', 1],
                [62, 'El Menzel', 1],
                [63, 'Guigou', 1],
                [64, 'Imouzzer Kandar', 1],
                [65, 'Imouzzer Marmoucha', 1],
                [66, 'Missour', 1],
                [67, 'Moulay Yaâcoub', 1],
                [68, 'Ouled Tayeb', 1],
                [69, 'Outat El Haj', 1],
                [70, 'Ribate El Kheir', 1],
                [71, 'Séfrou', 1],
                [72, 'Skhinate', 1],
                [73, 'Tafajight', 1],
                [74, 'Arbaoua', 1],
                [75, 'Aïn Dorij', 1],
                [76, 'Dar Gueddari', 1],
                [77, 'Had Kourt', 1],
                [78, 'Jorf El Melha', 1],
                [79, 'Kénitra', 1],
                [80, 'Khenichet', 1],
                [81, 'Lalla Mimouna', 1],
                [82, 'Mechra Bel Ksiri', 1],
                [83, 'Mehdia', 1],
                [84, 'Moulay Bousselham', 1],
                [85, 'Sidi Allal Tazi', 1],
                [86, 'Sidi Kacem', 1],
                [87, 'Sidi Slimane', 1],
                [88, 'Sidi Taibi', 1],
                [89, 'Sidi Yahya El Gharb', 1],
                [90, 'Souk El Arbaa', 1],
                [91, 'Akka', 1],
                [92, 'Assa', 1],
                [93, 'Bouizakarne', 1],
                [94, 'El Ouatia', 1],
                [95, 'Es-Semara', 1],
                [96, 'Fam El Hisn', 1],
                [97, 'Foum Zguid', 1],
                [98, 'Guelmim', 1],
                [99, 'Taghjijt', 1],
                [100, 'Tan-Tan', 1],
                [101, 'Tata', 1],
                [102, 'Zag', 1],
                [103, 'Marrakech', 1],
                [104, 'Ait Daoud', 1],
                [115, 'Amizmiz', 1],
                [116, 'Assahrij', 1],
                [117, 'Aït Ourir', 1],
                [118, 'Ben Guerir', 1],
                [119, 'Chichaoua', 1],
                [120, 'El Hanchane', 1],
                [121, 'El Kelaâ des Sraghna', 1],
                [122, 'Essaouira', 1],
                [123, 'Fraïta', 1],
                [124, 'Ghmate', 1],
                [125, 'Ighounane', 1],
                [126, 'Imintanoute', 1],
                [127, 'Kattara', 1],
                [128, 'Lalla Takerkoust', 1],
                [129, 'Loudaya', 1],
                [130, 'Lâattaouia', 1],
                [131, 'Moulay Brahim', 1],
                [132, 'Mzouda', 1],
                [133, 'Ounagha', 1],
                [134, 'Sid L Mokhtar', 1],
                [135, 'Sid Zouin', 1],
                [136, 'Sidi Abdallah Ghiat', 1],
                [137, 'Sidi Bou Othmane', 1],
                [138, 'Sidi Rahhal', 1],
                [139, 'Skhour Rehamna', 1],
                [140, 'Smimou', 1],
                [141, 'Tafetachte', 1],
                [142, 'Tahannaout', 1],
                [143, 'Talmest', 1],
                [144, 'Tamallalt', 1],
                [145, 'Tamanar', 1],
                [146, 'Tamansourt', 1],
                [147, 'Tameslouht', 1],
                [148, 'Tanalt', 1],
                [149, 'Zeubelemok', 1],
                [150, 'Meknès?', 1],
                [151, 'Khénifra', 1],
                [152, 'Agourai', 1],
                [153, 'Ain Taoujdate', 1],
                [154, 'MyAliCherif', 1],
                [155, 'Rissani', 1],
                [156, 'Amalou Ighriben', 1],
                [157, 'Aoufous', 1],
                [158, 'Arfoud', 1],
                [159, 'Azrou', 1],
                [160, 'Aïn Jemaa', 1],
                [161, 'Aïn Karma', 1],
                [162, 'Aïn Leuh', 1],
                [163, 'Aït Boubidmane', 1],
                [164, 'Aït Ishaq', 1],
                [165, 'Boudnib', 1],
                [166, 'Boufakrane', 1],
                [167, 'Boumia', 1],
                [168, 'El Hajeb', 1],
                [169, 'Elkbab', 1],
                [170, 'Er-Rich', 1],
                [171, 'Errachidia', 1],
                [172, 'Gardmit', 1],
                [173, 'Goulmima', 1],
                [174, 'Gourrama', 1],
                [175, 'Had Bouhssoussen', 1],
                [176, 'Haj Kaddour', 1],
                [177, 'Ifrane', 1],
                [178, 'Itzer', 1],
                [179, 'Jorf', 1],
                [180, 'Kehf Nsour', 1],
                [181, 'Kerrouchen', 1],
                [182, 'M haya', 1],
                [183, 'M rirt', 1],
                [184, 'Midelt', 1],
                [185, 'Moulay Ali Cherif', 1],
                [186, 'Moulay Bouazza', 1],
                [187, 'Moulay Idriss Zerhoun', 1],
                [188, 'Moussaoua', 1],
                [189, 'N Zalat Bni Amar', 1],
                [190, 'Ouaoumana', 1],
                [191, 'Oued Ifrane', 1],
                [192, 'Sabaa Aiyoun', 1],
                [193, 'Sebt Jahjouh', 1],
                [194, 'Sidi Addi', 1],
                [195, 'Tichoute', 1],
                [196, 'Tighassaline', 1],
                [197, 'Tighza', 1],
                [198, 'Timahdite', 1],
                [199, 'Tinejdad', 1],
                [200, 'Tizguite', 1],
                [201, 'Toulal', 1],
                [202, 'Tounfite', 1],
                [203, 'Zaouia Ifrane', 1],
                [204, 'Zaïda', 1],
                [205, 'Ahfir', 1],
                [206, 'Aklim', 1],
                [207, 'Al Aroui', 1],
                [208, 'Aïn Bni Mathar', 1],
                [209, 'Aïn Erreggada', 1],
                [210, 'Ben Taïeb', 1],
                [211, 'Berkane', 1],
                [212, 'Bni Ansar', 1],
                [213, 'Bni Chiker', 1],
                [214, 'Bni Drar', 1],
                [215, 'Bni Tadjite', 1],
                [216, 'Bouanane', 1],
                [217, 'Bouarfa', 1],
                [218, 'Bouhdila', 1],
                [219, 'Dar El Kebdani', 1],
                [220, 'Debdou', 1],
                [221, 'Douar Kannine', 1],
                [222, 'Driouch', 1],
                [223, 'El Aïoun Sidi Mellouk', 1],
                [224, 'Farkhana', 1],
                [225, 'Figuig', 1],
                [226, 'Ihddaden', 1],
                [227, 'Jaâdar', 1],
                [228, 'Jerada', 1],
                [229, 'Kariat Arekmane', 1],
                [230, 'Kassita', 1],
                [231, 'Kerouna', 1],
                [232, 'Laâtamna', 1],
                [233, 'Madagh', 1],
                [234, 'Midar', 1],
                [235, 'Nador', 1],
                [236, 'Naima', 1],
                [237, 'Oued Heimer', 1],
                [238, 'Oujda', 1],
                [239, 'Ras El Ma', 1],
                [240, 'Saïdia', 1],
                [241, 'Selouane', 1],
                [242, 'Sidi Boubker', 1],
                [243, 'Sidi Slimane Echcharaa', 1],
                [244, 'Talsint', 1],
                [245, 'Taourirt', 1],
                [246, 'Tendrara', 1],
                [247, 'Tiztoutine', 1],
                [248, 'Touima', 1],
                [249, 'Touissit', 1],
                [250, 'Zaïo', 1],
                [251, 'Zeghanghane', 1],
                [252, 'Rabat', 1],
                [253, 'Salé', 1],
                [254, 'Ain El Aouda', 1],
                [255, 'Harhoura', 1],
                [256, 'Khémisset', 1],
                [257, 'Oulmès', 1],
                [258, 'Rommani', 1],
                [259, 'Sidi Allal El Bahraoui', 1],
                [260, 'Sidi Bouknadel', 1],
                [261, 'Skhirat', 1],
                [262, 'Tamesna', 1],
                [263, 'Témara', 1],
                [264, 'Tiddas', 1],
                [265, 'Tiflet', 1],
                [266, 'Touarga', 1],
                [267, 'Agadir', 1],
                [268, 'Agdz', 1],
                [269, 'Agni Izimmer', 1],
                [270, 'Aït Melloul', 1],
                [271, 'Alnif', 1],
                [272, 'Anzi', 1],
                [273, 'Aoulouz', 1],
                [274, 'Aourir', 1],
                [275, 'Arazane', 1],
                [276, 'Aït Baha', 1],
                [277, 'Aït Iaâza', 1],
                [278, 'Aït Yalla', 1],
                [279, 'Ben Sergao', 1],
                [280, 'Biougra', 1],
                [281, 'Boumalne-Dadès', 1],
                [282, 'Dcheira El Jihadia', 1],
                [283, 'Drargua', 1],
                [284, 'El Guerdane', 1],
                [285, 'Harte Lyamine', 1],
                [286, 'Ida Ougnidif', 1],
                [287, 'Ifri', 1],
                [288, 'Igdamen', 1],
                [289, 'Ighil n Oumgoun', 1],
                [290, 'Imassine', 1],
                [291, 'Inezgane', 1],
                [292, 'Irherm', 1],
                [293, 'Kelaat-M Gouna', 1],
                [294, 'Lakhsas', 1],
                [295, 'Lakhsass', 1],
                [296, 'Lqliâa', 1],
                [297, 'M semrir', 1],
                [298, 'Massa [Maroc]', 1],
                [299, 'Megousse', 1],
                [300, 'Ouarzazate', 1],
                [301, 'Oulad Berhil', 1],
                [302, 'Oulad Teïma', 1],
                [303, 'Sarghine', 1],
                [304, 'Sidi Ifni', 1],
                [305, 'Skoura', 1],
                [306, 'Tabounte', 1],
                [307, 'Tafraout', 1],
                [308, 'Taghzout', 1],
                [309, 'Tagzen', 1],
                [310, 'Taliouine', 1],
                [311, 'Tamegroute', 1],
                [312, 'Tamraght', 1],
                [313, 'Tanoumrite Nkob Zagora', 1],
                [314, 'Taourirt ait zaghar', 1],
                [315, 'Taroudant', 1],
                [316, 'Temsia', 1],
                [317, 'Tifnit', 1],
                [318, 'Tisgdal', 1],
                [319, 'Tiznit', 1],
                [320, 'Toundoute', 1],
                [321, 'Zagora', 1],
                [322, 'Afourar', 1],
                [323, 'Aghbala', 1],
                [324, 'Azilal', 1],
                [325, 'Aït Majden', 1],
                [326, 'Beni Ayat', 1],
                [327, 'Béni Mellal', 1],
                [328, 'Bin elouidane', 1],
                [329, 'Bradia', 1],
                [330, 'Bzou', 1],
                [331, 'Dar Oulad Zidouh', 1],
                [332, 'Demnate', 1],
                [333, 'Dra a', 1],
                [334, 'El Ksiba', 1],
                [335, 'Foum Jamaa', 1],
                [336, 'Fquih Ben Salah', 1],
                [337, 'Kasba Tadla', 1],
                [338, 'Ouaouizeght', 1],
                [339, 'Oulad Ayad', 1],
                [340, 'Oulad M Barek', 1],
                [341, 'Oulad Yaich', 1],
                [342, 'Sidi Jaber', 1],
                [343, 'Souk Sebt Oulad Nemma', 1],
                [344, 'Zaouïat Cheikh', 1],
                [345, 'Tanger', 1],
                [346, 'Tétouan', 1],
                [347, 'Akchour', 1],
                [348, 'Assilah', 1],
                [349, 'Bab Berred', 1],
                [350, 'Bab Taza', 1],
                [351, 'Brikcha', 1],
                [352, 'Chefchaouen', 1],
                [353, 'Dar Bni Karrich', 1],
                [354, 'Dar Chaoui', 1],
                [355, 'Fnideq', 1],
                [356, 'Gueznaia', 1],
                [357, 'Jebha', 1],
                [358, 'Karia', 1],
                [359, 'Khémis Sahel', 1],
                [360, 'Ksar El Kébir', 1],
                [361, 'Larache', 1],
                [362, 'M diq', 1],
                [363, 'Martil', 1],
                [364, 'Moqrisset', 1],
                [365, 'Oued Laou', 1],
                [366, 'Oued Rmel', 1],
                [367, 'Ouezzane', 1],
                [368, 'Point Cires', 1],
                [369, 'Sidi Lyamani', 1],
                [370, 'Sidi Mohamed ben Abdallah el-Raisuni', 1],
                [371, 'Zinat', 1],
                [372, 'Ajdir', 1],
                [373, 'Aknoul', 1],
                [374, 'Al Hoceïma', 1],
                [375, 'Aït Hichem', 1],
                [376, 'Bni Bouayach', 1],
                [377, 'Bni Hadifa', 1],
                [378, 'Ghafsai', 1],
                [379, 'Guercif', 1],
                [380, 'Imzouren', 1],
                [381, 'Inahnahen', 1],
                [382, 'Issaguen [Ketama]', 1],
                [383, 'Karia [El Jadida]', 1],
                [384, 'Karia Ba Mohamed', 1],
                [385, 'Oued Amlil', 1],
                [386, 'Oulad Zbair', 1],
                [387, 'Tahla', 1],
                [388, 'Tala Tazegwaght', 1],
                [389, 'Tamassint', 1],
                [390, 'Taounate', 1],
                [391, 'Targuist', 1],
                [392, 'Taza', 1],
                [393, 'Taïnaste', 1],
                [394, 'Thar Es-Souk', 1],
                [395, 'Tissa', 1],
                [396, 'Tizi Ouasli', 1],
                [397, 'Laayoune', 1],
                [398, 'El Marsa', 1],
                [399, 'Tarfaya', 1],
                [400, 'Boujdour', 1],
                [401, 'Awsard', 1],
                [402, 'Oued-Eddahab ', 1],
                [403, 'Stehat', 1],
                [404, 'Aït Attab', 1]
        );
    }
}
